<?php
return array(
	//'配置项'=>'配置值'
	'MEMBER_PAGE_SIZE'=>15,//后台列表默认显示条数
	'VIP_PAGE_SIZE'=>15,//后台列表默认显示条数
	'MEMBER_MAX_UPLOAD'=>2000000,//后台上传文件最大限制2M
	'MEMBER_UPLOAD_DIR'=>'UF/Uploads/',//后台上传目录
    'MEMBER_HEAD_DIR'=>'Style/header/customavatars/',//头像上传目录
	'MEMBER_ALLOW_EXTS'=>array('jpg', 'gif', 'png', 'jpeg' ,'doc' ,'docx' ,'pdf', 'rar' , 'zip'),//允许上传的附件类型
	'SHOW_UPLOAD_W'	=> "100,300",
	'SHOW_UPLOAD_H'	=> "100,300",
	'ALBUM_UPLOAD_W'	=> "190,300",
	'ALBUM_UPLOAD_H'	=> "190,300",
	
	'BANK_NAME'=>array(
			'icbc'=>'工商银行',
			'3002'=>'工商银行',
			'ccb'=>'建设银行',
			'3003'=>'建设银行',
			'bocsh'=>'中国银行',
			'boc'=>'中国银行',
			'3026'=>'中国银行',
			'abc'=>'农业银行',
			'3005'=>'农业银行',
			'psbc'=>'邮政储蓄',
			'3038'=>'邮政储蓄',
			'comm'=>'交通银行',
			'3020'=>'交通银行',
			'cmb'=>'招商银行',
			'3001'=>'招商银行',
			'cncb'=>'中信银行',
			'3039'=>'中信银行',
			'cmbc'=>'民生银行',
			'cmsb'=>'民生银行',
			'3006'=>'民生银行',
			'ceb'=>'光大银行',
			'3022'=>'光大银行',
			'bob'=>'北京银行',
			'bjb'=>'北京银行',
			'3032'=>'北京银行',
			'cib'=>'兴业银行',
			'3009'=>'兴业银行',
			'gdb'=>'广发银行',
			'3036'=>'广发银行',
			'hxb'=>'华夏银行',
			'spdb'=>'浦发银行',
			'3004'=>'浦发银行',
			'pab'=>'平安银行',
			'3035'=>'平安银行',

		),
	 'BANK_ICO'=>array(
			'icbc'=>'ico_icbc',
			'3002'=>'ico_icbc',
			'ccb'=>'ico_ccb',
			'3003'=>'ico_ccb',
			'bocsh'=>'ico_boc',
			'boc'=>'ico_boc',
			'3026'=>'ico_boc',
			'abc'=>'ico_abc',
			'3005'=>'ico_abc',
			'psbc'=>'ico_post',
			'3038'=>'ico_post',
			'comm'=>'ico_boco',
			'3020'=>'ico_boco',
			'cmb'=>'ico_cmb',
			'3001'=>'ico_cmb',
			'cncb'=>'ico_ecitic',
			'3039'=>'ico_ecitic',
			'cmbc'=>'ico_cmbc',
			'cmsb'=>'ico_cmbc',
			'3006'=>'ico_cmbc',
			'ceb'=>'ico_cebb',
			'3022'=>'ico_cebb',
			'bob'=>'ico_bob',
			'bjb'=>'ico_bob',
			'3032'=>'ico_bob',
			'cib'=>'ico_cib',
			'3009'=>'ico_cib',
			'gdb'=>'ico_gdb',
			'3036'=>'ico_gdb',
			'hxb'=>'ico_hxb',
			'spdb'=>'ico_spdb',
			'3004'=>'ico_spdb',
			'pab'=>'ico_pingan',
			'3035'=>'ico_pingan',

		),
);
?>